/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputProps } from "./components/internal/orama-input/orama-input";
import { TextProps } from "./components/internal/orama-text/orama-text";
export { InputProps } from "./components/internal/orama-input/orama-input";
export { TextProps } from "./components/internal/orama-text/orama-text";
export namespace Components {
    interface OramaChat {
    }
    interface OramaInput {
        "label"?: InputProps['label'];
        "labelForScreenReaders"?: InputProps['labelForScreenReaders'];
        "name": InputProps['name'];
        "size"?: InputProps['size'];
        "type"?: InputProps['type'];
    }
    interface OramaText {
        /**
          * it defines the HTML tag to be used
         */
        "as"?: TextProps['as'];
        /**
          * it defines how it should look like
         */
        "styledAs"?: TextProps['styledAs'];
    }
    interface OramaTextarea {
        "maxRows": number | string;
        "minRows": number | string;
        "placeholder": string;
        "value": string | null;
    }
    interface SearchBox {
        "color": 'dark' | 'light' | 'system';
        "themeConfig": { colors: { light: { primaryColor: string }; dark: { primaryColor: string } } };
    }
}
declare global {
    interface HTMLOramaChatElement extends Components.OramaChat, HTMLStencilElement {
    }
    var HTMLOramaChatElement: {
        prototype: HTMLOramaChatElement;
        new (): HTMLOramaChatElement;
    };
    interface HTMLOramaInputElement extends Components.OramaInput, HTMLStencilElement {
    }
    var HTMLOramaInputElement: {
        prototype: HTMLOramaInputElement;
        new (): HTMLOramaInputElement;
    };
    interface HTMLOramaTextElement extends Components.OramaText, HTMLStencilElement {
    }
    var HTMLOramaTextElement: {
        prototype: HTMLOramaTextElement;
        new (): HTMLOramaTextElement;
    };
    interface HTMLOramaTextareaElement extends Components.OramaTextarea, HTMLStencilElement {
    }
    var HTMLOramaTextareaElement: {
        prototype: HTMLOramaTextareaElement;
        new (): HTMLOramaTextareaElement;
    };
    interface HTMLSearchBoxElement extends Components.SearchBox, HTMLStencilElement {
    }
    var HTMLSearchBoxElement: {
        prototype: HTMLSearchBoxElement;
        new (): HTMLSearchBoxElement;
    };
    interface HTMLElementTagNameMap {
        "orama-chat": HTMLOramaChatElement;
        "orama-input": HTMLOramaInputElement;
        "orama-text": HTMLOramaTextElement;
        "orama-textarea": HTMLOramaTextareaElement;
        "search-box": HTMLSearchBoxElement;
    }
}
declare namespace LocalJSX {
    interface OramaChat {
    }
    interface OramaInput {
        "label"?: InputProps['label'];
        "labelForScreenReaders"?: InputProps['labelForScreenReaders'];
        "name"?: InputProps['name'];
        "size"?: InputProps['size'];
        "type"?: InputProps['type'];
    }
    interface OramaText {
        /**
          * it defines the HTML tag to be used
         */
        "as"?: TextProps['as'];
        /**
          * it defines how it should look like
         */
        "styledAs"?: TextProps['styledAs'];
    }
    interface OramaTextarea {
        "maxRows"?: number | string;
        "minRows"?: number | string;
        "placeholder"?: string;
        "value"?: string | null;
    }
    interface SearchBox {
        "color"?: 'dark' | 'light' | 'system';
        "themeConfig"?: { colors: { light: { primaryColor: string }; dark: { primaryColor: string } } };
    }
    interface IntrinsicElements {
        "orama-chat": OramaChat;
        "orama-input": OramaInput;
        "orama-text": OramaText;
        "orama-textarea": OramaTextarea;
        "search-box": SearchBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "orama-chat": LocalJSX.OramaChat & JSXBase.HTMLAttributes<HTMLOramaChatElement>;
            "orama-input": LocalJSX.OramaInput & JSXBase.HTMLAttributes<HTMLOramaInputElement>;
            "orama-text": LocalJSX.OramaText & JSXBase.HTMLAttributes<HTMLOramaTextElement>;
            "orama-textarea": LocalJSX.OramaTextarea & JSXBase.HTMLAttributes<HTMLOramaTextareaElement>;
            "search-box": LocalJSX.SearchBox & JSXBase.HTMLAttributes<HTMLSearchBoxElement>;
        }
    }
}
