/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OramaP {
    }
    interface SearchBox {
        "color": 'dark' | 'light' | 'system';
        "themeConfig": { colors: { light: { primaryColor: string }; dark: { primaryColor: string } } };
    }
}
declare global {
    interface HTMLOramaPElement extends Components.OramaP, HTMLStencilElement {
    }
    var HTMLOramaPElement: {
        prototype: HTMLOramaPElement;
        new (): HTMLOramaPElement;
    };
    interface HTMLSearchBoxElement extends Components.SearchBox, HTMLStencilElement {
    }
    var HTMLSearchBoxElement: {
        prototype: HTMLSearchBoxElement;
        new (): HTMLSearchBoxElement;
    };
    interface HTMLElementTagNameMap {
        "orama-p": HTMLOramaPElement;
        "search-box": HTMLSearchBoxElement;
    }
}
declare namespace LocalJSX {
    interface OramaP {
    }
    interface SearchBox {
        "color"?: 'dark' | 'light' | 'system';
        "themeConfig"?: { colors: { light: { primaryColor: string }; dark: { primaryColor: string } } };
    }
    interface IntrinsicElements {
        "orama-p": OramaP;
        "search-box": SearchBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "orama-p": LocalJSX.OramaP & JSXBase.HTMLAttributes<HTMLOramaPElement>;
            "search-box": LocalJSX.SearchBox & JSXBase.HTMLAttributes<HTMLSearchBoxElement>;
        }
    }
}
