/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputProps } from "./components/internal/Form/Input";
import { ParagraphProps } from "./components/internal/Typography/Paragraph";
import { SmallProps } from "./components/internal/Typography/Small";
import { SpanProps } from "./components/internal/Typography/Span";
export { InputProps } from "./components/internal/Form/Input";
export { ParagraphProps } from "./components/internal/Typography/Paragraph";
export { SmallProps } from "./components/internal/Typography/Small";
export { SpanProps } from "./components/internal/Typography/Span";
export namespace Components {
    interface OramaChat {
    }
    interface OramaInput {
        "label"?: InputProps['label'];
        "labelForScreenReaders"?: InputProps['labelForScreenReaders'];
        "name": InputProps['name'];
        "placeholder"?: InputProps['placeholder'];
        "size"?: InputProps['size'];
    }
    interface OramaParagraph {
        "as"?: ParagraphProps['as'];
    }
    interface OramaSmall {
        "as"?: SmallProps['as'];
    }
    interface OramaSpan {
        "as"?: SpanProps['as'];
    }
    interface OramaTextarea {
        "maxRows": number | string;
        "minRows": number | string;
        "placeholder": string;
        "value": string | null;
    }
    interface SearchBox {
        "color": 'dark' | 'light' | 'system';
        "themeConfig": { colors: { light: { primaryColor: string }; dark: { primaryColor: string } } };
    }
}
declare global {
    interface HTMLOramaChatElement extends Components.OramaChat, HTMLStencilElement {
    }
    var HTMLOramaChatElement: {
        prototype: HTMLOramaChatElement;
        new (): HTMLOramaChatElement;
    };
    interface HTMLOramaInputElement extends Components.OramaInput, HTMLStencilElement {
    }
    var HTMLOramaInputElement: {
        prototype: HTMLOramaInputElement;
        new (): HTMLOramaInputElement;
    };
    interface HTMLOramaParagraphElement extends Components.OramaParagraph, HTMLStencilElement {
    }
    var HTMLOramaParagraphElement: {
        prototype: HTMLOramaParagraphElement;
        new (): HTMLOramaParagraphElement;
    };
    interface HTMLOramaSmallElement extends Components.OramaSmall, HTMLStencilElement {
    }
    var HTMLOramaSmallElement: {
        prototype: HTMLOramaSmallElement;
        new (): HTMLOramaSmallElement;
    };
    interface HTMLOramaSpanElement extends Components.OramaSpan, HTMLStencilElement {
    }
    var HTMLOramaSpanElement: {
        prototype: HTMLOramaSpanElement;
        new (): HTMLOramaSpanElement;
    };
    interface HTMLOramaTextareaElement extends Components.OramaTextarea, HTMLStencilElement {
    }
    var HTMLOramaTextareaElement: {
        prototype: HTMLOramaTextareaElement;
        new (): HTMLOramaTextareaElement;
    };
    interface HTMLSearchBoxElement extends Components.SearchBox, HTMLStencilElement {
    }
    var HTMLSearchBoxElement: {
        prototype: HTMLSearchBoxElement;
        new (): HTMLSearchBoxElement;
    };
    interface HTMLElementTagNameMap {
        "orama-chat": HTMLOramaChatElement;
        "orama-input": HTMLOramaInputElement;
        "orama-paragraph": HTMLOramaParagraphElement;
        "orama-small": HTMLOramaSmallElement;
        "orama-span": HTMLOramaSpanElement;
        "orama-textarea": HTMLOramaTextareaElement;
        "search-box": HTMLSearchBoxElement;
    }
}
declare namespace LocalJSX {
    interface OramaChat {
    }
    interface OramaInput {
        "label"?: InputProps['label'];
        "labelForScreenReaders"?: InputProps['labelForScreenReaders'];
        "name"?: InputProps['name'];
        "placeholder"?: InputProps['placeholder'];
        "size"?: InputProps['size'];
    }
    interface OramaParagraph {
        "as"?: ParagraphProps['as'];
    }
    interface OramaSmall {
        "as"?: SmallProps['as'];
    }
    interface OramaSpan {
        "as"?: SpanProps['as'];
    }
    interface OramaTextarea {
        "maxRows"?: number | string;
        "minRows"?: number | string;
        "placeholder"?: string;
        "value"?: string | null;
    }
    interface SearchBox {
        "color"?: 'dark' | 'light' | 'system';
        "themeConfig"?: { colors: { light: { primaryColor: string }; dark: { primaryColor: string } } };
    }
    interface IntrinsicElements {
        "orama-chat": OramaChat;
        "orama-input": OramaInput;
        "orama-paragraph": OramaParagraph;
        "orama-small": OramaSmall;
        "orama-span": OramaSpan;
        "orama-textarea": OramaTextarea;
        "search-box": SearchBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "orama-chat": LocalJSX.OramaChat & JSXBase.HTMLAttributes<HTMLOramaChatElement>;
            "orama-input": LocalJSX.OramaInput & JSXBase.HTMLAttributes<HTMLOramaInputElement>;
            "orama-paragraph": LocalJSX.OramaParagraph & JSXBase.HTMLAttributes<HTMLOramaParagraphElement>;
            "orama-small": LocalJSX.OramaSmall & JSXBase.HTMLAttributes<HTMLOramaSmallElement>;
            "orama-span": LocalJSX.OramaSpan & JSXBase.HTMLAttributes<HTMLOramaSpanElement>;
            "orama-textarea": LocalJSX.OramaTextarea & JSXBase.HTMLAttributes<HTMLOramaTextareaElement>;
            "search-box": LocalJSX.SearchBox & JSXBase.HTMLAttributes<HTMLSearchBoxElement>;
        }
    }
}
