import type { StoryObj, Meta } from '@storybook/web-components'
import type { Components } from '@orama/wc-components'

const meta: Meta<Components.OramaChatMessagesContainer> = {
  title: 'Components/Internal/Chat',
  component: 'orama-chat-messages-container',
  tags: ['autodocs'],
} satisfies Meta

export default meta
type Story = StoryObj<Components.OramaChatMessagesContainer>

const MARKDOWN_MESSAGE = `
Marked - Markdown Parser
========================

[Marked] lets you convert [Markdown] into HTML.  Markdown is a simple text format whose goal is to be very easy to read and write, even when not converted to HTML.  This demo page will let you type anything you like and see how it gets converted.  Live.  No more waiting around.

How To Use The Demo
-------------------

1. Type in stuff on the left.
2. See the live updates on the right.

\`\`\`javascript
  function helloWorld() {
    console.log('Hello World!')
  }
\`\`\`
`

export const ChatMessagesContainer: Story = {
  args: {
    interactions: [
      {
        query: 'Some random question?',
        response: MARKDOWN_MESSAGE,
        sources: [
          {
            title: 'Paris',
            description: 'The capital of France',
            path: 'https://en.wikipedia.org/wiki/Paris',
          },
        ],
        relatedQueries: ['Some related question?', 'Another related question?'],
        // biome-ignore lint/suspicious/noExplicitAny: Enum is rasing error here...
        status: 'done' as any,
        interactionId: '123',
      },
      {
        query: 'How to get started with something?',
        response: 'Some random answer generated By the LLM.',
        sources: [
          {
            title: 'Paris',
            description: 'The capital of France',
            path: 'https://en.wikipedia.org/wiki/Paris',
          },
          {
            title: 'Argentina',
            description: 'The capital of France',
            path: 'https://en.wikipedia.org/wiki/Paris',
          },
          {
            title: 'Brazil',
            description: 'The capital of France',
            path: 'https://en.wikipedia.org/wiki/Paris',
          },
        ],
        relatedQueries: ['Some related question?', 'Another related question?'],
        // biome-ignore lint/suspicious/noExplicitAny: Enum is rasing error here...
        status: 'done' as any,
        interactionId: '456',
        latest: true,
      },
    ],
  },
}
