name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Component Library
        run: pnpm run build